- name: My first task
  hosts: local
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello World!

    - name: Create noel user
      ansible.builtin.user:
        groups: ["docker"]
        append: true
        name: noel

    # Docker
    - name: Install docker
      ansible.builtin.package:
        name: docker
        state: present
    - name: Enable docker unit
      ansible.builtin.systemd_service:
        name: docker.socket
        enabled: true

    # Programs
    - name: Install Steam
      ansible.builtin.package:
        name: steam
        state: present
    - name: Install VS code (OSS)
      ansible.builtin.package:
        name: code
        state: present
    - name: Install Teamspeak
      ansible.builtin.package:
        name: teamspeak3
        state: present
    #- name: Install PrusaSlicer
    #  ansible.builtin.package:
    #    name: prusa-slicer
    #    state: present

    # Misc packages
    - name: Install ansible-lint
      ansible.builtin.package:
        name: ansible-lint
        state: present
    - name: Install nvidia container toolkit
      ansible.builtin.package:
        name: nvidia-container-toolkit
        state: present
    # XBOX controller
    - name: Install xbox controller package
      ansible.builtin.package:
        name: xone-dkms
        state: present
    - name: Install xbox dongle firmware
      ansible.builtin.package:
        name: xone-dongle-firmware
        state: present
    - name: Install stow
      ansible.builtin.package:
        name: stow
        state: present

    # Git Config
    - name: Update git email
      community.general.git_config:
        name: user.email
        scope: system
        value: "noeljarling@gmail.com"
    - name: Update git name
      community.general.git_config:
        name: user.name
        scope: system
        value: "Noel Jarling"
    - name: Mark dotfiles folder safe
      community.general.git_config:
        name: safe.directory
        scope: global
        value: "/home/noel/dotfiles"

    # Pull git Config
    - name: Pull dotfiles
      ansible.builtin.git:
        accept_newhostkey: true
        dest: "/home/noel/dotfiles"
        repo: "https://github.com/NoelJarling/dotfiles.git"
    - name: Apply dotfiles (stow)
      ansible.builtin.command:
        chdir: "/home/noel/dotfiles"
        cmd: "stow --apply ."
    - name: Apply dotfiles (stow)
      ansible.builtin.command:
        chdir: "/home/noel/dotfiles"
        cmd: "stow --apply ."
